config/routes.rb
CampusFreeloader::Application.routes.draw do
  
  
  resources :follows

  root :to => "events#recent"
  
  get "admin/login"
  
  post "admin/login"
  
  get "admin/logout"

  post "events/new"
  
  get "events/recent"
  
  get "users/register"
  
  post "users/register"
  
  get "users/aboutus"
  
  get "users/suggestion"
  
  get "users/policy"
  
  post "events/invitefriend"
  
  resources :attends
  
  resources :users

  resources :events

  resources :buildings
  
 

  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :building
  has_many :attends
  belongs_to :user
  def event_date
    start_time.day
  end
  
  def event_hours
    start_time.strftime("%H:%M").to_s + "-" + end_time.strftime("%H:%M").to_s
  end
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  
  def invitefriend
    user = User.find(session[:user_id])
    event = Event.find(params[:id])
    
    params[:invitees].each do |id|
      invitee = User.find(id)
      Invitation.invitefriend(user, invitee, event).deliver
      
    end
    redirect_to :back, :notice => "Invitation sent"
  end
  
  def recent
    #@events = Event.all
     @events=Array.new
      @buildings=Array.new
      
     @events = Event.find(:all, :conditions => ["end_time > ?", Time.now], :order => "end_time") 

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end
  
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])
    
    @attend = Attend.new
    @attend.event_id = @event.id
    @attend.user_id = session[:user_id]
    @attend.attend = Date.today
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  def invite(event)
    Invitation.invite(@event).deliver
  end
  
  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<br /><%= link_to attend.user.username, attend.user %>

app/views/events/_event.html.erb
<tr>
  <!--<td><%= event.id %></td>-->
    <td><%= event.desc %></td>
    <td><%= event.building.buildname %></td>
    <td><%= event.start_time.to_date %></td>
    <td>
      <% if event.idcheck %>
        <%= "Yes"%>
        <%else%>
        <%= "No"%>
      <% end %>  
    </td>
  
    <td><%= link_to 'Detail', event %></td>
        <% if session[:user_id].nil?%>
      <% elsif User.find(session[:user_id]).username == "admin" or event.user_id == session[:user_id] %>
    <td><% link_to 'Edit', edit_event_path(event) %></td>
    <td><% link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
    <%end%>
</tr>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="class">
    <div id="buildselect">
      <%= f.label :Where %><br />
      <%  buildings = Building.all %>
      <%  ids_and_names = buildings.map do |b| [b.buildname, b.id] end %>
      <%= f.select :building_id, ids_and_names, :prompt => "select a building.."%>  Didn't find this building? <%= link_to 'Add New Building', :action=> "new", :controller =>'buildings' %>
    </div>
  </div>
  <div class="field">
    <%= f.label :What_to_eat %><br />
    <%= f.text_field :desc %>
  </div>

    <div class="field">
    <%= f.label :When_starts%><br />
    <%= f.datetime_select :start_time%>
  </div>
  
  <div class="field">
    <%= f.label :ends %><br />
    <%= f.datetime_select :end_time %>
  </div>
  
  <div class="field">
    <%= f.label :Who_privides_food %><br />
    <%= f.text_field :host %>
  </div> 
  <div class="field">
    <%= f.label :Why %> (event)<br />
    <%= f.text_field :eventname %>
  </div>

  <div class="field">
    <%= f.label :Do_they_check_SUID? %><br />
    <%= f.check_box :idcheck %>Yes
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :created_at, :value => Time.now %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_invite.html.erb
  <%= form_tag(:action => 'invitefriend') do %>
  <%= submit_tag 'Invite Friends', :action => 'invitefriend' %>
  <div id="invfri">
  <%= hidden_field_tag :id, @event.id %>
  <% cu=User.find(session[:user_id])%>
  <% cu.followers.each do |f| %>
  <input type="checkbox" name="invitees[]" value="<%= f.id %>" /> <%= f.username%> <br />
  <% end %>
  </div>
  <% # = button_to 'invite friends', :action=>'invitefriend', :id=> @event.id, :confirmation=> 'Would you like ' %>
  <% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Free Food Events</h1>

<table cellpadding="2">
  <tr>
   <!-- <th>id</th>-->
    <th>What to eat</th>
    <th>Where</th>
    <th>When</th>
    <th>Require ID</th>
    <th></th>

  </tr>
 <%= render :partial => 'event', :collection => @events %>

</table>

<br />
<div id="newevt">
  <div id="newevttxt">
    Found free food?
  </div>
  <div id="newevtbtn">
  <%= button_to 'Tell us!', :action=> "new", :controller =>'events' %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Free Food!</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/recent.html.erb
<div id="recent">
  <h1>Look out, Free Food Around!</h1>
  <%= render :partial => "shared/map", :object => @events, :as => 'events' %>
     <table>
  <tr>
    <th>What to eat</th>
    <th>Where</th>
    <th>When</th>
    <th>Require ID</th>
    <th></th>

  </tr>
 <%= render :partial => 'event', :collection => @events %>

</table>

<br />
<div id="newevt">
  <div id="newevttxt">
    Found free food?
  </div>
  <div id="newevtbtn">
  <%= button_to 'Tell us!', :action=> "new", :controller =>'events' %>
  </div>
</div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div id="eventsshow">
<p>
  <b>What's goint on: </b>
  <%= @event.eventname %>
</p>

<p>
  <b>Anything to eat? </b>
  <%= @event.desc %>
</p>

<p>
  <b>Host:</b>
  <%= @event.host %>
</p>

<p>
  <b>Where:</b>
  <%= @event.building.buildname %>
</p>

<p>
  <b>ID Required:</b>
      <% if @event.idcheck %>
        <%= "Yes"%>
        <%else%>
        <%= "No"%>
      <% end %>  
</p>

<p>
  <b>Created By:</b>
  <%= @event.user.username %>
</p>

<p>
  <b>Date:</b>
  <%= @event.start_time.to_date %>
</p>

<p>
  <b>Time:</b>
  <%= @event.event_hours %>
  <%if @event.end_time.hour < 12 %>
  <%= "Morning"%>
  <%elsif @event.end_time.hour < 17 %>
    <%= "Afternoon"%>
    <%else%>
      <%= "Evening"%>
    <%end%>
</p>


<div id="attendbtn">
  <% evats = Attend.find_all_by_event_id(@event.id).map { |a| a.user_id } %>
  <% if evats.include?(session[:user_id])%>
Attending
  <% else %>
  <%= render '/attends/form' %>
  <%end%>
</div>

<div id="funcbtn">
<% if @event.user_id = session[:user_id] %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>
<%= link_to 'Back', events_path %> 
</div>

</div>
<div id="attendee">
  <%if @event.attends.count >0 %>
    <br /><b>Who is attending</b>
    <%= render :partial => 'attend', :collection => @event.attends %>
  <% else %>
      nobody attending
  <%end%>
</div>

<div id="invite">
<%= render 'invite' %>
</div>