config/routes.rb
CampusFreeloader::Application.routes.draw do
  
  
  resources :follows

  root :to => "events#recent"
  
  get "admin/login"
  
  post "admin/login"
  
  get "admin/logout"

  post "events/new"
  
  get "events/recent"
  
  get "users/register"
  
  post "users/register"
  
  get "users/aboutus"
  
  get "users/suggestion"
  
  get "users/policy"
  
  post "events/invitefriend"
  
  resources :attends
  
  resources :users

  resources :events

  resources :buildings
  
 

  
  

end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :users
  has_many :events
  
  def fulladdress
    addrln1 + ","+ addrln2 + "," + city + ","+ state + ","+ zip
  end
  
  

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  # GET /buildings
  # GET /buildings.xml
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.xml
  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.xml
  def new
    @building = Building.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    @building = Building.find(params[:id])
  end

  # POST /buildings
  # POST /buildings.xml
  def create
    require 'net/http'
    @building = Building.new(params[:building])

    uri = "http://maps.google.com/maps/api/geocode/xml?address=" + @building.fulladdress.gsub(' ','+') + "&sensor=false"
    resp = Net::HTTP.get(URI.parse(uri))
    noko_resp = Nokogiri::XML(resp)
    
    noko_resp.xpath("//GeocodeResponse/result/geometry/location").each do |node|
        #puts node.xpath('lat').inner_text.inspect
        #puts node.xpath('lng').inner_text.inspect
        @building.lat = node.xpath('lat').inner_text
        @building.lon = node.xpath('lng').inner_text
    end
    
    
    respond_to do |format|
      if @building.save
        format.html { redirect_to(@building, :notice => 'Building was successfully created.') }
        format.xml  { render :xml => @building, :status => :created, :location => @building }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @building.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.xml
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to(@building, :notice => 'Building was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @building.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.xml
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to(buildings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buildname %><br />
    <%= f.text_field :buildname %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :addrln1 %><br />
    <%= f.text_field :addrln1 %>
  </div>
  <div class="field">
    <%= f.label :addrln2 %><br />
    <%= f.text_field :addrln2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing Buildings</h1>

<table>
  <tr>
    <th>Building</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buildings.each do |building| %>
   <tr>
    <td><%= building.buildname %></td>
    <td><%= building.desc %></td>
    <td><%= link_to 'More..', building %></td>
    <% if session[:user_id].nil?%>
      <%elsif User.find(session[:user_id]).username == "admin" %>
    <td><%= link_to 'Edit', edit_building_path(building) %></td>
    <td><%= link_to 'Destroy', building, :confirm => 'Are you sure?', :method => :delete %></td>
    <%  end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Building Name:</b>
  <%= @building.buildname %>
</p>

<p>
  <b>Description:</b>
  <%= @building.desc %>
</p>

<p>
  <b>Address Line 1:</b>
  <%= @building.addrln1 %>
</p>

<p>
  <b>Address Line 2:</b>
  <%= @building.addrln2 %>
</p>

<p>
  <b>City:</b>
  <%= @building.city %>
</p>

<p>
  <b>State:</b>
  <%= @building.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @building.zip %>
</p>
<p>
  <b>lat:</b>
  <%= @building.lat %>
</p>
<p>
  <b>lon:</b>
  <%= @building.lon %>
</p>

    <% if session[:user_id].nil?%>
      <%elsif User.find(session[:user_id]).username == "admin" %>
<%= link_to 'Edit', edit_building_path(@building) %> |
    <% end %>
<%= link_to 'Back', buildings_path %>