config/routes.rb
CampusFreeloader::Application.routes.draw do
  
  
  resources :follows

  root :to => "events#recent"
  
  get "admin/login"
  
  post "admin/login"
  
  get "admin/logout"

  post "events/new"
  
  get "events/recent"
  
  get "users/register"
  
  post "users/register"
  
  get "users/aboutus"
  
  get "users/suggestion"
  
  get "users/policy"
  
  post "events/invitefriend"
  
  resources :attends
  
  resources :users

  resources :events

  resources :buildings
  
 

  
  

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :following_user, :class_name=> 'User'
  belongs_to :followed_user, :class_name=> 'User'
  
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  # GET /follows
  # GET /follows.xml
  
  before_filter :authenticate, :except => 'index'
  # => ['show','login','index', 'register','aboutus']
  def authenticate
    if session[:user_id].nil?
      flash[:alert] = 'You need to login to Proceed.'
      redirect_to :controller => 'admin', :action => 'login'
    end
  end
  
  def index
    @follows = Follow.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @follows }
    end
  end

  # GET /follows/1
  # GET /follows/1.xml
  def show
    @follow = Follow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @follow }
    end
  end

  # GET /follows/new
  # GET /follows/new.xml
  def new
    @follow = Follow.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @follow }
    end
  end

  # GET /follows/1/edit
  def edit
    @follow = Follow.find(params[:id])
  end

  # POST /follows
  # POST /follows.xml
  def create
    @follow = Follow.new(params[:follow])

    respond_to do |format|
      if @follow.save
        format.html { redirect_to :back }
        format.xml  { render :xml => @follow, :status => :created, :location => @follow }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @follow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /follows/1
  # PUT /follows/1.xml
  def update
    @follow = Follow.find(params[:id])

    respond_to do |format|
      if @follow.update_attributes(params[:follow])
        format.html { redirect_to(@follow, :notice => 'Follow was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @follow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.xml
  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to(follows_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"> 
  <%  if session[:user_id].nil? %>
   <%= f.hidden_field :following_user_id, :value => 0  %> <% else %>
   <%= f.hidden_field :following_user_id, :value => @follow.following_user.id  %>
  <%  end %>
   <%= f.hidden_field :followed_user_id, :value => @follow.followed_user.id %>

  </div>

  <div class="actions">
    <%= f.submit :value =>'Follow'%>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing Follows</h1>

<table>
  <tr>
    <th>Following user</th>
    <th>Followed user</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @follows.each do |follow| %>
  <tr>
    <td><%= follow.following_user.username %></td>
    <td><%= follow.followed_user.username %></td>
    <td><%= link_to 'Show', follow %></td>
    <% if session[:user_id].nil?%>
      <% elsif User.find(session[:user_id]).username == "admin" %>
    <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
    <td><%= link_to 'Destroy', follow, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Following user:</b>
  <%= @follow.following_user_id %>
</p>

<p>
  <b>Followed user:</b>
  <%= @follow.followed_user_id %>
</p>

    <% if session[:user_id].nil?%>
      <% elsif User.find(session[:user_id]).username == "admin" %>
<%= link_to 'Edit', edit_follow_path(@follow) %> |

<% end %>
<%= link_to 'Back', follows_path %>