config/routes.rb
CampusFreeloader::Application.routes.draw do
  
  
  resources :follows

  root :to => "events#recent"
  
  get "admin/login"
  
  post "admin/login"
  
  get "admin/logout"

  post "events/new"
  
  get "events/recent"
  
  get "users/register"
  
  post "users/register"
  
  get "users/aboutus"
  
  get "users/suggestion"
  
  get "users/policy"
  
  post "events/invitefriend"
  
  resources :attends
  
  resources :users

  resources :events

  resources :buildings
  
 

  
  

end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  # GET /attends
  # GET /attends.xml
  def index
    @attends = Attend.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attends }
    end
  end

  # GET /attends/1
  # GET /attends/1.xml
  def show
    @attend = Attend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attend }
    end
  end

  # GET /attends/new
  # GET /attends/new.xml
  def new
    @attend = Attend.new
    
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attend }
    end
  end

  # GET /attends/1/edit
  def edit
    @attend = Attend.find(params[:id])
  end

  # POST /attends
  # POST /attends.xml
  def create
    @attend = Attend.new(params[:attend])

    respond_to do |format|
      if @attend.save
        format.html { redirect_to :back }
        format.xml  { render :xml => @attend, :status => :created, :location => @attend }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attends/1
  # PUT /attends/1.xml
  def update
    @attend = Attend.find(params[:id])

    respond_to do |format|
      if @attend.update_attributes(params[:attend])
        format.html { redirect_to(@attend, :notice => 'Attend was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.xml
  def destroy
    @attend = Attend.find(params[:id])
    @attend.destroy

    respond_to do |format|
      format.html { redirect_to(attends_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/views/attends/_form.html.erb
<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% @attend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit :value => 'Eat Here!!' %>
  </div>
  
  <div class="field">
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
    <%= f.hidden_field :event_id, :value =>@event.id %>
    <%= f.hidden_field :attend, :value => Date.today %>
  </div>
<% end %>

app/views/attends/edit.html.erb
<h1>Editing attend</h1>

<%= render 'form' %>

<%= link_to 'Show', @attend %> |
<%= link_to 'Back', attends_path %>

app/views/attends/index.html.erb
<h1>Listing Attends</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th>Attend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attends.each do |attend| %>
  <tr>
    <td><%= attend.user.username%></td>
    <td><%= attend.event.eventname %></td>
    <td><%= attend.attend %></td>
    <td><%= link_to 'Show', attend %></td>
    <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
    <td><%= link_to 'Destroy', attend, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attend', new_attend_path %>

app/views/attends/new.html.erb
<h1>New attend</h1>

<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% @attend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p> 
  You are attending <%= params[:event_id] %>.
  </p>
  <div class="field">
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :event_id, :value =>params[:event_id] %>
  </div>
  <div class="field">
     <%= f.hidden_field :attend, :value => Date.today %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', attends_path %>

app/views/attends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @attend.user_id %>
</p>

<p>
  <b>Event:</b>
  <%= @attend.event_id %>
</p>

<p>
  <b>Attend:</b>
  <%= @attend.attend %>
</p>


<%= link_to 'Edit', edit_attend_path(@attend) %> |
<%= link_to 'Back', attends_path %>